package com.smartdental.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Index;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Entity
@Table(
        name = "clinical_notes",
        indexes = {@Index(name = "idx_clinical_notes_patient", columnList = "patient_id")})
@Getter
@Setter
@NoArgsConstructor
public class ClinicalNote extends BaseEntity {

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "appointment_id")
    private Appointment appointment;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "patient_id", nullable = false)
    private User patient;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "dentist_id", nullable = false)
    private User dentist;

    /** Raw clinical shorthand as typed by the dentist, e.g. "Tooth #14 DO composite, deep caries". */
    @Column(nullable = false, columnDefinition = "TEXT")
    private String shorthand;

    /** Plain-English summary generated by the AI translation engine. */
    @Column(name = "ai_summary", columnDefinition = "TEXT")
    private String aiSummary;

    @Column(name = "cdt_code")
    private String cdtCode;

    @Column(name = "tooth_number")
    private Integer toothNumber;

    @Column(name = "patient_visible", nullable = false)
    private boolean patientVisible = false;
}
